language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36

sudo: false

install:
  - pip install coveralls
  - pip install tox

script: tox

after_success: coveralls
